services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: maintify_db
      POSTGRES_USER: maintify_user
      POSTGRES_PASSWORD: maintify_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maintify_user -d maintify_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=api/app.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://maintify_user:maintify_password@db:5432/maintify_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - ./plugins:/app/plugins
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data:
