#!/usr/bin/env bash
# =============================================================================
# Maintify — developer environment setup
# =============================================================================
# Generates secrets, creates .env, builds and starts all services, then
# creates a real system-admin account through rbac-cli.
#
# Usage:
#   bash scripts/dev-setup.sh            # full interactive setup
#   bash scripts/dev-setup.sh --reset    # tear down everything and start fresh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

# ── terminal colours ─────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}▸ $*${RESET}"; }
success() { echo -e "${GREEN}✔ $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠ $*${RESET}"; }
error()   { echo -e "${RED}✖ $*${RESET}" >&2; exit 1; }
header()  { echo -e "\n${BOLD}$*${RESET}"; echo -e "${BOLD}$(printf '─%.0s' {1..60})${RESET}"; }

# ── prerequisite check ───────────────────────────────────────────────────────
header "Checking prerequisites"

check_cmd() {
  command -v "$1" >/dev/null 2>&1 || error "'$1' is not installed or not in PATH"
  success "$1 found ($(command -v "$1"))"
}

check_cmd docker
docker compose version >/dev/null 2>&1 || error "docker compose plugin not available"
success "docker compose found"
check_cmd openssl
check_cmd curl

# ── optional reset ───────────────────────────────────────────────────────────
if [[ "${1:-}" == "--reset" ]]; then
  warn "Tearing down existing stack and removing .env …"
  docker compose down -v --remove-orphans 2>/dev/null || true
  rm -f .env
  success "Reset complete"
fi

# ── generate .env ────────────────────────────────────────────────────────────
header "Environment configuration"

if [[ -f .env ]]; then
  warn ".env already exists — skipping generation (use --reset to regenerate)"
  # shellcheck disable=SC1091
  set -a; source .env; set +a
else
  info "Generating cryptographic secrets …"
  JWT_SECRET="$(openssl rand -hex 64)"
  BUILDER_API_KEY="$(openssl rand -hex 32)"

  echo ""
  echo -e "${BOLD}Database credentials${RESET}"
  printf "DB user   [maintify]: "; read -r _db_user
  DB_USER="${_db_user:-maintify}"

  printf "DB name   [maintify_core]: "; read -r _db_name
  DB_NAME="${_db_name:-maintify_core}"

  printf "DB password (leave blank to auto-generate): "; read -rs _db_pass; echo
  if [[ -z "${_db_pass}" ]]; then
    DB_PASSWORD="$(openssl rand -hex 16)"
    info "Auto-generated DB password: ${DB_PASSWORD}"
  else
    DB_PASSWORD="${_db_pass}"
  fi

  echo ""
  echo -e "${BOLD}Admin account${RESET}"
  printf "First name: "; read -r ADMIN_FIRST_NAME
  [[ -z "${ADMIN_FIRST_NAME}" ]] && error "First name is required"

  printf "Last name: "; read -r ADMIN_LAST_NAME
  [[ -z "${ADMIN_LAST_NAME}" ]] && error "Last name is required"

  printf "Email: "; read -r ADMIN_EMAIL
  [[ -z "${ADMIN_EMAIL}" ]] && error "Email is required"

  printf "Username [${ADMIN_EMAIL%%@*}]: "; read -r _admin_user
  ADMIN_USERNAME="${_admin_user:-${ADMIN_EMAIL%%@*}}"

  while true; do
    printf "Password (min 12 chars): "; read -rs ADMIN_PASSWORD; echo
    [[ "${#ADMIN_PASSWORD}" -ge 12 ]] && break
    warn "Password must be at least 12 characters"
  done
  printf "Confirm password: "; read -rs _confirm; echo
  [[ "${ADMIN_PASSWORD}" != "${_confirm}" ]] && error "Passwords do not match"

  info "Writing .env …"
  cat > .env <<EOF
# =============================================================================
# Maintify — local development environment
# Generated by scripts/dev-setup.sh — DO NOT COMMIT
# =============================================================================

# --- Database ---
DB_USER=${DB_USER}
DB_NAME=${DB_NAME}
DB_PASSWORD=${DB_PASSWORD}

# --- Builder service ---
BUILDER_API_KEY=${BUILDER_API_KEY}

# --- Core service ---
JWT_SECRET=${JWT_SECRET}

# --- Initial admin (used once at first run, can be removed afterwards) ---
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
EOF
  success ".env written"
fi

# Re-export all vars so they are available to docker compose
set -a; source .env; set +a

# ── build & start ─────────────────────────────────────────────────────────────
header "Building and starting services"
info "Running docker compose up --build -d …"
docker compose up --build -d
success "Docker Compose started"

# ── wait for core health ──────────────────────────────────────────────────────
header "Waiting for services to become healthy"

CORE_URL="http://localhost:8080/health"
MAX_WAIT=120   # seconds
WAITED=0
INTERVAL=5

info "Polling ${CORE_URL} (up to ${MAX_WAIT}s) …"
while true; do
  HTTP_CODE="$(curl -s -o /dev/null -w "%{http_code}" "${CORE_URL}" 2>/dev/null || echo "000")"
  if [[ "${HTTP_CODE}" == "200" ]]; then
    success "Core API is healthy"
    break
  fi
  if [[ ${WAITED} -ge ${MAX_WAIT} ]]; then
    error "Core did not become healthy within ${MAX_WAIT}s. Check: docker compose logs core"
  fi
  echo -n "."
  sleep "${INTERVAL}"
  WAITED=$((WAITED + INTERVAL))
done

# ── create system admin ───────────────────────────────────────────────────────
header "Creating system administrator"

# Check if admin already exists (idempotency)
EXISTING_ADMIN="$(docker compose exec -T core ./rbac-cli list-users 2>/dev/null | grep -c "${ADMIN_EMAIL}" || true)"
if [[ "${EXISTING_ADMIN}" -gt 0 ]]; then
  warn "Admin account ${ADMIN_EMAIL} already exists — skipping creation"
else
  info "Creating admin account for ${ADMIN_EMAIL} …"
  docker compose exec -T \
    -e ADMIN_EMAIL="${ADMIN_EMAIL}" \
    -e ADMIN_USERNAME="${ADMIN_USERNAME}" \
    -e ADMIN_PASSWORD="${ADMIN_PASSWORD}" \
    -e ADMIN_FIRST_NAME="${ADMIN_FIRST_NAME}" \
    -e ADMIN_LAST_NAME="${ADMIN_LAST_NAME}" \
    core ./rbac-cli create-admin
  success "Admin account created"
fi

# ── done ──────────────────────────────────────────────────────────────────────
header "Setup complete"

echo ""
echo -e "${GREEN}${BOLD}Maintify is running!${RESET}"
echo ""
echo -e "  ${BOLD}Frontend${RESET}      http://localhost:3000"
echo -e "  ${BOLD}Core API${RESET}      http://localhost:8080"
echo -e "  ${BOLD}Builder API${RESET}   http://localhost:8081"
echo -e "  ${BOLD}Health${RESET}        http://localhost:8080/health"
echo ""
echo -e "  ${BOLD}Admin email${RESET}   ${ADMIN_EMAIL}"
echo -e "  ${BOLD}Admin user${RESET}    ${ADMIN_USERNAME}"
echo ""
echo -e "${CYAN}Useful commands:${RESET}"
echo -e "  docker compose logs -f core      # tail core logs"
echo -e "  docker compose logs -f           # tail all logs"
echo -e "  docker compose down              # stop the stack"
echo -e "  docker compose down -v           # stop + remove volumes"
echo ""
